Algoritmo "Lista02Ex04"
// Disciplina   : [Linguagem e Lógica de Programação orientada a Objetos]
// Professor   : Aldo Henrique
// Descrição   : Imprimir em ordem decrescente e crescente.
// Autor(a)    : André José CPD: 29099
// Data atual  : 11/03/2019
Var
   n1, n2, n3, d: inteiro

Inicio
   escreva("Digite o primeiro número:")
   leia(n1)

   escreva("Digite o segundo número:")
   leia(n2)

   escreva("Digite o terceiro número:")
   leia(n1)

Fimalgoritmo