Algoritmo "Slide-Ex1C"
// Disciplina   : [Linguagem e Lógica de Programação orientada a Objetos]
// Professor   : Aldo Henrique
// Descrição   : Impar ou Par
// Autor(a)    : André José CPD: 29099
// Data atual  : 11/03/2019
Var
   n1: inteiro

Inicio
      escreva("Informe um número: ")
      leia(n1)
      
      se n1 mod 2 = 0 então
         escreva(" O número: ", n1, " é par")
      senao
           escreva("O número ", n1, " é ímpar")
      fimse


Fimalgoritmo